# Generated by Django 3.0.5 on 2020-05-09 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ankiety', '0003_delete_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('choice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ankiety.Choice')),
                ('user_id', models.CharField(max_length=200)),
                ('voted_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_content_type', to='ankiety.Choice')),
            ],
            bases=('ankiety.choice',),
        ),
    ]
