# Generated by Django 3.0.5 on 2020-05-09 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ankiety', '0005_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
