# Generated by Django 3.0.5 on 2020-05-13 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ankiety', '0007_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='voted_choice',
        ),
    ]
