# Generated by Django 3.0.5 on 2020-05-13 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ankiety', '0008_remove_vote_voted_choice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
