# Generated by Django 3.0.5 on 2020-05-13 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ankiety', '0010_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='voted_choice',
        ),
    ]
