# Generated by Django 3.0.5 on 2020-05-13 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ankiety', '0013_vote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
