# Generated by Django 3.0.5 on 2020-05-13 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ankiety', '0014_delete_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('voted_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_content_type', to='ankiety.Choice')),
                ('voted_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_content_type', to='ankiety.Question')),
            ],
        ),
    ]
